"""Overworld tile art (16x16)."""

import pygame

from .. import palette as P
from . import shading
from .shading import M

PAL = {
    "g": P.GRASS, "G": P.GRASS_L, "h": P.GRASS_D,
    "l": P.TALLGRASS, "L": P.TALLGRASS_L, "k": P.TALLGRASS_D,
    "t": P.TREE, "T": P.TREE_L, "y": P.TREE_D, "r": P.TRUNK,
    "p": P.PATH, "P": P.PATH_L, "q": P.PATH_D,
    "w": P.WATER, "W": P.WATER_L, "v": P.WATER_D,
    "s": P.STONE, "S": P.STONE_L, "x": P.STONE_D,
    "b": P.WALL, "B": P.WALL_L, "d": P.WALL_D,
    "o": P.ROOF, "O": P.ROOF_L, "n": P.ROOF_D,
    "f": P.FLOWER_A, "F": P.FLOWER_B,
    "c": P.CREAM, "K": P.BLACK, "e": P.GREY_D, "E": P.GREY, "j": P.GREY_L,
    "i": P.SAND, "m": P.WHITE, "u": (136, 96, 56), "z": (96, 64, 40),
    "n": (152, 56, 56), "f": (248, 224, 128), "Y": (248, 240, 200),
    "P": (238, 234, 222), "h": (150, 146, 138),
    "p": P.STONE, "y": (216, 176, 72),
}

TALLGRASS = [
    "gGggggghgggGgggg",
    "ggg.gg..g.gg.ggg",
    "g.L..L.L..L..L.g",
    ".Lk.LkL.kLl.Lk.L",
    "Llk.lkl.klL.lkLl",
    "lkl.lkl.lkl.lkll",
    "lkl.lkl.lkl.lklk",
    "kkllkkllkkllkkll",
    "lkllkkllkkllkkll",
    ".L.L..L.L..L.L..",
    "Lkl.LklkLl.Lkl.L",
    "lkllkkl.lkllkkll",
    "lkllkkl.lkllkkll",
    "kkllkkllkkllkkll",
    "kkllkkllkkllkkll",
    "gkghgkgggkgggkgg",
]

# Trees are billboards in the diorama, so they are authored upright and
# taller than a tile: canopy lit from the upper left, trunk at the base.
TREE = [
    "......tttt......",
    "....ttTTTTtt....",
    "...tTTTTTTTTt...",
    "..tTTTTTTTTTyt..",
    ".tTTTTTTTTTTyyt.",
    ".tTTTTTTTTTTyyt.",
    "tTTTTTTTTTTTyyyt",
    "tTTTTTTTTTTyyyyt",
    "tTTTTTTTTTTTyyyt",
    "tTTTTTTTTTTyyyyt",
    ".tTTTTTTTTTyyyt.",
    ".tTTTTTTTTyyyyt.",
    "..tTTTTTTTyyyt..",
    "..tTTTTTTyyyyt..",
    "...tTTTTTyyyt...",
    "....ttTTyyytt...",
    "......trrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    ".....rrRrrrt....",
    "....rrrrrrrrt...",
    "...tttttttttt...",
    "................",
    "................",
]

FLOWERS = [
    "gGggggghgggGgggg",
    "gggg.f.ggggggggg",
    "ggg.fff.gggg.F.g",
    "gggg.f.ggggg.F.g",
    "ggggggggggggFFFg",
    "gGggggggggggFFFg",
    "gggggggggggg.F.g",
    "gg.F.ggggggggggg",
    "gg.F.gggggg.f.gg",
    "ggFFFgggggg.f.gg",
    "ggFFFggggggfffgg",
    "gg.F.gggggg.f.gg",
    "gggggggggggggggg",
    "gGgg.f.gggggggGg",
    "ggg.fff.ggggggg.",
    "gggg.f.gggggGggg",
]

WATER = [
    "wwwwwwwwwwwwwwww",
    "wWWwwwwwwwwWWWww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwvvwwwwwwwwvvww",
    "wwwwwwwwvvwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwWWWwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wvvwwwwwwwwwwvvw",
    "wwwwwwwvvwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwWWwwwwwwwWWwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
]

WATER_B = [
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwWWwwwwwwwWWwww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wvvwwwwwwwwwwvvw",
    "wwwwwwwvvwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwWWWwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwvvwwwwwwwwvvww",
    "wwwwwwwwvvwwwwww",
    "wwwwwwwwwwwwwwww",
    "wWWwwwwwwwwWWWww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
]

ROCK = [
    "gGggggghgggGgggg",
    "ggggSSSSSggggggg",
    "gggSSSSSSSSgggGg",
    "ggSSsssssSSSgggg",
    "gSSssssssssSSggg",
    "gSssssxxsssssSgg",
    "gSsssxxxxssssSgg",
    "gSssxxxxxxsssSgg",
    "gSsxxxxxxxxssSgg",
    "gSxxxxxxxxxxsSgg",
    "ggxxxxxxxxxxxSgg",
    "gghxxxxxxxxxhggg",
    "ggghhxxxxxhhgggg",
    "gGgghhhhhhggggGg",
    "gggggghhhggggggg",
    "gggggggggggggggg",
]

SIGN = [
    "gGggggghgggGgggg",
    "ggggggggggggggg.",
    "gguuuuuuuuuuuugg",
    "guBBBBBBBBBBBBug",
    "guBeeeeeeeeeeBug",
    "guBeBBeeBBeeeBug",
    "guBeeeeeeeeeeBug",
    "guBeeBBeeBBeeBug",
    "guBeeeeeeeeeeBug",
    "guBBBBBBBBBBBBug",
    "gguuuuuuuuuuuugg",
    "gggggzuuzggggggg",
    "gGgggzuuzgggggGg",
    "gggggzuuzggggggg",
    "gggghzzzzhgggggg",
    "gggggghhgggggggg",
]

# --- Village building pieces -------------------------------------------------
ROOF_L_ = [
    "gggggggggggggggO",
    "ggggggggggggggOO",
    "gggggggggggggOOo",
    "ggggggggggggOOoo",
    "gggggggggggOOooo",
    "ggggggggggOOoooo",
    "gggggggggOOooooo",
    "ggggggggOOoooooo",
    "gggggggOOooooooo",
    "ggggggOOoooooooo",
    "gggggOOooooooooo",
    "ggggOOoooooooooo",
    "gggOOooooooooooo",
    "ggOOoooooooonnnn",
    "gOOoooooooonnnnn",
    "OOnnnnnnnnnnnnnn",
]
ROOF_M = [
    "OOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOO",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
]
ROOF_R = [
    "Oggggggggggggggg",
    "OOgggggggggggggg",
    "oOOggggggggggggg",
    "ooOOgggggggggggg",
    "oooOOggggggggggg",
    "ooooOOgggggggggg",
    "oooooOOggggggggg",
    "ooooooOOgggggggg",
    "oooooooOOggggggg",
    "ooooooooOOgggggg",
    "oooooooooOOggggg",
    "ooooooooooOOgggg",
    "oooooooooooOOggg",
    "nnnnoooooooOOgg.",
    "nnnnnoooooooOOg.",
    "nnnnnnnnnnnnnOO.",
]
WALL_PLAIN = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "dddddddddddddddd",
    "hgGggghggggGgggg",
]
WALL_WINDOW = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzzzzzzzzzzbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "dddddddddddddddd",
    "hgGggghggggGgggg",
]
DOOR = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuzzuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuKuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "ddzzzzzzzzzzzzdd",
    "hgGggghggggGgggg",
]

# --- Shrine --------------------------------------------------------------
# Six tiles laid out in two rows: a torii-style gate with a hanging scale,
# standing over a carved altar block.
SHRINE_TOP_L = [
    "gggggggggggggggg",
    "ggggggggggggggnn",
    "gggggggggnnnnnnn",
    "ggggggggonnnnnnn",
    "gggggggggooooooo",
    "gggggggggggggggg",
    "ggggggggggnnnnnn",
    "ggggggggggnnnnnn",
    "ggggggggggoooooo",
    "gggggggggggggggg",
    "ggggggggggoSSSSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
]
SHRINE_TOP_M = [
    "gggggggggggggggg",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "oooooooooooooooo",
    "gggggggggggggggg",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "oooooooooooooooo",
    "gggggggooggggggg",
    "ggggggoyyogggggg",
    "gggggoyffyoggggg",
    "ggggooyffyooogggg"[:16],
    "gggggoyffyoggggg",
    "ggggggoyyogggggg",
    "gggggggooggggggg",
]
SHRINE_TOP_R = [
    "gggggggggggggggg",
    "nngggggggggggggg",
    "nnnnnnnggggggggg",
    "nnnnnnnoggggggggg"[:16],
    "oooooooggggggggg",
    "gggggggggggggggg",
    "nnnnnngggggggggg",
    "nnnnnngggggggggg",
    "oooooogggggggggg",
    "gggggggggggggggg",
    "oSSSSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
]
SHRINE_BOT_L = [
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "pppppppppoSSSSSo",
    "ppppppppoSSSSSSS",
    "pppppppooxxxxxxx",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]
SHRINE_BOT_M = [
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppoooooooooppppp"[:16],
    "pppoSSSSSSSSoppp",
    "pppoSssyysssoppp",
    "pppoSsyYYysSoppp",
    "pppoSsyYYysSoppp",
    "pppoSssyysssoppp",
    "pppoSssssssSoppp",
    "pppoSSSSSSSSoppp",
    "pppoxxxxxxxxoppp",
    "pppoooooooooppp."[:16],
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]
SHRINE_BOT_R = [
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSSSSSopppppppppp"[:16],
    "SSSSSSSopppppppp",
    "xxxxxxxoopppppppp"[:16],
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]

# Marble column, authored upright like the trees.
COLUMN = [
    "..pppppppppppp..",
    ".pPPPPPPPPPPPPp.",
    ".pPPPPPPPPPPPPp.",
    "..pppppppppppp..",
    "...pPPPPPPPPp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "..pppppppppppp..",
    ".pPPPPPPPPPPPPp.",
    ".pPPPPPPPPPPPPp.",
    "..pppppppppppp..",
    "..hhhhhhhhhhhh..",
    "................",
]

RUBBLE = [
    "gggggggggggggggg",
    "ggggggggggggggGg",
    "gggppppgggggpppg",
    "ggpPPPPpgggpPPpg",
    "ggpPPPPpggpPPPpg",
    "gghppppggghpppgg",
    "gggggggggggggggg",
    "ggpppppgggggggGg",
    "gpPPPPPpgggppggg",
    "gpPPPPPpggpPPpgg",
    "ghpppppgghpppggg",
    "gggggggggggggggg",
    "gGggggggggggggGg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
]

FOUNTAIN = [
    "SSSSSSSSSSSSSSSS",
    "SxxxxxxxxxxxxxxS",
    "SxwwwwwwwwwwwwxS",
    "SxwWWwwwwwwWWwxS",
    "SxwwwwWWWwwwwwxS",
    "SxwwwSSSSSwwwwxS",
    "SxwwSSjjjSSwwwxS",
    "SxwwSjmmmjSwwwxS",
    "SxwwSjmmmjSwwwxS",
    "SxwwSSjjjSSwwwxS",
    "SxwwwSSSSSwwwwxS",
    "SxwwwwWWWwwwwwxS",
    "SxwWWwwwwwwWWwxS",
    "SxwwwwwwwwwwwwxS",
    "SxxxxxxxxxxxxxxS",
    "SSSSSSSSSSSSSSSS",
]

LEDGE = [
    "gggggggggggggggg",
    "hhhhhhhhhhhhhhhh",
    "qqqqqqqqqqqqqqqq",
    "PqqPqqqqPqqqqPqq",
    "qqqqqqqqqqqqqqqq",
    "qqqqqqqqqqqqqqqq",
    "hhhhhhhhhhhhhhhh",
    "gGggggghgggGgggg",
    "gggggggggggggggg",
    "gggGgggggghggggg",
    "gggggggggggggggg",
    "gGgggghgggggggGg",
    "gggggggggggggggg",
    "ggghggggggGggggg",
    "gggggggggggggggg",
    "gGggggghgggGgggg",
]


# --------------------------------------------------------------------------
# Props are billboards in the diorama, so they run through the same lighting
# pipeline as the monsters: material maps in, lit sprites at twice the size
# out. Each entry also names the characters that are only background in the
# original top-down art - those become transparent, or the prop would stand
# in a square patch of its own grass.
# --------------------------------------------------------------------------
PROP_ART = {
    "tree": (TREE, "gGh"),
    "rock": (ROCK, "gGh"),
    "sign": (SIGN, "gGh"),
    "rubble": (RUBBLE, "gG"),
    "column": (COLUMN, ""),
    "fountain": (FOUNTAIN, ""),
    "wall": (WALL_PLAIN, "gGh"),
    "window": (WALL_WINDOW, "gGh"),
    "door": (DOOR, "gGh"),
    "roof_l": (ROOF_L_, "gGh"),
    "roof_m": (ROOF_M, ""),
    "roof_r": (ROOF_R, "gGh"),
    "shrine_tl": (SHRINE_TOP_L, "gGh"),
    "shrine_tm": (SHRINE_TOP_M, "gGh"),
    "shrine_tr": (SHRINE_TOP_R, "gGh"),
    "shrine_bl": (SHRINE_BOT_L, "p"),
    "shrine_bm": (SHRINE_BOT_M, "p"),
    "shrine_br": (SHRINE_BOT_R, "p"),
}

# One material table for every prop, since the art shares a palette.
MATERIALS = {
    "g": M(P.GRASS, "plant"), "G": M(P.GRASS_L, "plant"),
    "h": M(P.GRASS_D, "plant"),
    "l": M(P.TALLGRASS, "plant"), "L": M(P.TALLGRASS_L, "plant"),
    "k": M(P.TALLGRASS_D, "plant"),
    "t": M((62, 128, 82), "plant"), "T": M((104, 172, 100), "plant"),
    "y": M((40, 92, 68), "plant"),
    "r": M((112, 78, 50), "plant"), "R": M((150, 112, 76), "plant"),
    "p": M(P.PATH, "stone"), "P": M((238, 234, 222), "stone"),
    "q": M(P.PATH_D, "stone"),
    "w": M(P.WATER, "gem", emissive=0.2),
    "W": M(P.WATER_L, "gem", emissive=0.35),
    "v": M(P.WATER_D, "gem"),
    "s": M(P.STONE, "stone"), "S": M(P.STONE_L, "stone"),
    "x": M(P.STONE_D, "stone"),
    "b": M(P.WALL, "stone"), "B": M(P.WALL_L, "stone"),
    "d": M(P.WALL_D, "stone"),
    "o": M(P.ROOF, "stone"), "O": M(P.ROOF_L, "stone"),
    "n": M((152, 56, 56), "stone"),
    "f": M((248, 224, 128), "gem", emissive=0.6),
    "Y": M((248, 240, 200), "gem", emissive=0.7),
    "F": M(P.FLOWER_B, "plant"),
    "c": M(P.CREAM, "cloth"), "K": M(P.BLACK, "matte"),
    "e": M(P.GREY_D, "stone"), "E": M(P.GREY, "stone"),
    "j": M(P.GREY_L, "stone"),
    "i": M(P.SAND, "stone"), "m": M(P.WHITE, "cloth"),
    "u": M((136, 96, 56), "plant"), "z": M((96, 64, 40), "plant"),
}


def _strip(rows, background):
    if not background:
        return rows
    table = {ord(c): "." for c in background}
    return [r.translate(table) for r in rows]


def build_props():
    """Every standing prop, lit and at twice its authored size."""
    out = {}
    for name, (rows, background) in PROP_ART.items():
        out[name] = shading.render(_strip(rows, background), MATERIALS)
    return out


def build():
    """Backwards-compatible flat surface table (used for silhouettes)."""
    return build_props()
