"""Overworld tile art (16x16)."""

import pygame
from .. import palette as P
from ..pixelart import make, ground_tile

PAL = {
    "g": P.GRASS, "G": P.GRASS_L, "h": P.GRASS_D,
    "l": P.TALLGRASS, "L": P.TALLGRASS_L, "k": P.TALLGRASS_D,
    "t": P.TREE, "T": P.TREE_L, "y": P.TREE_D, "r": P.TRUNK,
    "p": P.PATH, "P": P.PATH_L, "q": P.PATH_D,
    "w": P.WATER, "W": P.WATER_L, "v": P.WATER_D,
    "s": P.STONE, "S": P.STONE_L, "x": P.STONE_D,
    "b": P.WALL, "B": P.WALL_L, "d": P.WALL_D,
    "o": P.ROOF, "O": P.ROOF_L, "n": P.ROOF_D,
    "f": P.FLOWER_A, "F": P.FLOWER_B,
    "c": P.CREAM, "K": P.BLACK, "e": P.GREY_D, "E": P.GREY, "j": P.GREY_L,
    "i": P.SAND, "m": P.WHITE, "u": (136, 96, 56), "z": (96, 64, 40),
    "n": (152, 56, 56), "f": (248, 224, 128), "Y": (248, 240, 200),
    "P": (238, 234, 222), "h": (150, 146, 138),
    "p": P.STONE, "y": (216, 176, 72),
}

TALLGRASS = [
    "gGggggghgggGgggg",
    "ggg.gg..g.gg.ggg",
    "g.L..L.L..L..L.g",
    ".Lk.LkL.kLl.Lk.L",
    "Llk.lkl.klL.lkLl",
    "lkl.lkl.lkl.lkll",
    "lkl.lkl.lkl.lklk",
    "kkllkkllkkllkkll",
    "lkllkkllkkllkkll",
    ".L.L..L.L..L.L..",
    "Lkl.LklkLl.Lkl.L",
    "lkllkkl.lkllkkll",
    "lkllkkl.lkllkkll",
    "kkllkkllkkllkkll",
    "kkllkkllkkllkkll",
    "gkghgkgggkgggkgg",
]

# Trees are billboards in the diorama, so they are authored upright and
# taller than a tile: canopy lit from the upper left, trunk at the base.
TREE = [
    "......tttt......",
    "....ttTTTTtt....",
    "...tTTTTTTTTt...",
    "..tTTTTTTTTTyt..",
    ".tTTTTTTTTTTyyt.",
    ".tTTTTTTTTTTyyt.",
    "tTTTTTTTTTTTyyyt",
    "tTTTTTTTTTTyyyyt",
    "tTTTTTTTTTTTyyyt",
    "tTTTTTTTTTTyyyyt",
    ".tTTTTTTTTTyyyt.",
    ".tTTTTTTTTyyyyt.",
    "..tTTTTTTTyyyt..",
    "..tTTTTTTyyyyt..",
    "...tTTTTTyyyt...",
    "....ttTTyyytt...",
    "......trrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    "......rRrrt.....",
    ".....rrRrrrt....",
    "....rrrrrrrrt...",
    "...tttttttttt...",
    "................",
    "................",
]

FLOWERS = [
    "gGggggghgggGgggg",
    "gggg.f.ggggggggg",
    "ggg.fff.gggg.F.g",
    "gggg.f.ggggg.F.g",
    "ggggggggggggFFFg",
    "gGggggggggggFFFg",
    "gggggggggggg.F.g",
    "gg.F.ggggggggggg",
    "gg.F.gggggg.f.gg",
    "ggFFFgggggg.f.gg",
    "ggFFFggggggfffgg",
    "gg.F.gggggg.f.gg",
    "gggggggggggggggg",
    "gGgg.f.gggggggGg",
    "ggg.fff.ggggggg.",
    "gggg.f.gggggGggg",
]

WATER = [
    "wwwwwwwwwwwwwwww",
    "wWWwwwwwwwwWWWww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwvvwwwwwwwwvvww",
    "wwwwwwwwvvwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwWWWwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wvvwwwwwwwwwwvvw",
    "wwwwwwwvvwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwWWwwwwwwwWWwww",
    "wwwwwwwwwwwwwwww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
]

WATER_B = [
    "wwwwwwwwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwWWwwwwwwwWWwww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wvvwwwwwwwwwwvvw",
    "wwwwwwwvvwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwwwWWWwwwwwwwww",
    "wwwwwwwwwwwwwwww",
    "wwvvwwwwwwwwvvww",
    "wwwwwwwwvvwwwwww",
    "wwwwwwwwwwwwwwww",
    "wWWwwwwwwwwWWWww",
    "wwwwwwwWWwwwwwww",
    "wwwwwwwwwwwwwwww",
]

ROCK = [
    "gGggggghgggGgggg",
    "ggggSSSSSggggggg",
    "gggSSSSSSSSgggGg",
    "ggSSsssssSSSgggg",
    "gSSssssssssSSggg",
    "gSssssxxsssssSgg",
    "gSsssxxxxssssSgg",
    "gSssxxxxxxsssSgg",
    "gSsxxxxxxxxssSgg",
    "gSxxxxxxxxxxsSgg",
    "ggxxxxxxxxxxxSgg",
    "gghxxxxxxxxxhggg",
    "ggghhxxxxxhhgggg",
    "gGgghhhhhhggggGg",
    "gggggghhhggggggg",
    "gggggggggggggggg",
]

SIGN = [
    "gGggggghgggGgggg",
    "ggggggggggggggg.",
    "gguuuuuuuuuuuugg",
    "guBBBBBBBBBBBBug",
    "guBeeeeeeeeeeBug",
    "guBeBBeeBBeeeBug",
    "guBeeeeeeeeeeBug",
    "guBeeBBeeBBeeBug",
    "guBeeeeeeeeeeBug",
    "guBBBBBBBBBBBBug",
    "gguuuuuuuuuuuugg",
    "gggggzuuzggggggg",
    "gGgggzuuzgggggGg",
    "gggggzuuzggggggg",
    "gggghzzzzhgggggg",
    "gggggghhgggggggg",
]

# --- Village building pieces -------------------------------------------------
ROOF_L_ = [
    "gggggggggggggggO",
    "ggggggggggggggOO",
    "gggggggggggggOOo",
    "ggggggggggggOOoo",
    "gggggggggggOOooo",
    "ggggggggggOOoooo",
    "gggggggggOOooooo",
    "ggggggggOOoooooo",
    "gggggggOOooooooo",
    "ggggggOOoooooooo",
    "gggggOOooooooooo",
    "ggggOOoooooooooo",
    "gggOOooooooooooo",
    "ggOOoooooooonnnn",
    "gOOoooooooonnnnn",
    "OOnnnnnnnnnnnnnn",
]
ROOF_M = [
    "OOOOOOOOOOOOOOOO",
    "OOOOOOOOOOOOOOOO",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "oooooooooooooooo",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
]
ROOF_R = [
    "Oggggggggggggggg",
    "OOgggggggggggggg",
    "oOOggggggggggggg",
    "ooOOgggggggggggg",
    "oooOOggggggggggg",
    "ooooOOgggggggggg",
    "oooooOOggggggggg",
    "ooooooOOgggggggg",
    "oooooooOOggggggg",
    "ooooooooOOgggggg",
    "oooooooooOOggggg",
    "ooooooooooOOgggg",
    "oooooooooooOOggg",
    "nnnnoooooooOOgg.",
    "nnnnnoooooooOOg.",
    "nnnnnnnnnnnnnOO.",
]
WALL_PLAIN = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "dddddddddddddddd",
    "hgGggghggggGgggg",
]
WALL_WINDOW = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzWWWWzWWWWzbB",
    "BbbzzzzzzzzzzbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "BbbbbbbbbbbbbbbB",
    "dddddddddddddddd",
    "hgGggghggggGgggg",
]
DOOR = [
    "BBBBBBBBBBBBBBBB",
    "BbbbbbbbbbbbbbbB",
    "BbbzzzzzzzzzzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuzzuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuKuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "BbbzuuuuuuuuzbbB",
    "ddzzzzzzzzzzzzdd",
    "hgGggghggggGgggg",
]

# --- Shrine --------------------------------------------------------------
# Six tiles laid out in two rows: a torii-style gate with a hanging scale,
# standing over a carved altar block.
SHRINE_TOP_L = [
    "gggggggggggggggg",
    "ggggggggggggggnn",
    "gggggggggnnnnnnn",
    "ggggggggonnnnnnn",
    "gggggggggooooooo",
    "gggggggggggggggg",
    "ggggggggggnnnnnn",
    "ggggggggggnnnnnn",
    "ggggggggggoooooo",
    "gggggggggggggggg",
    "ggggggggggoSSSSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
    "ggggggggggoSssSo",
]
SHRINE_TOP_M = [
    "gggggggggggggggg",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "oooooooooooooooo",
    "gggggggggggggggg",
    "nnnnnnnnnnnnnnnn",
    "nnnnnnnnnnnnnnnn",
    "oooooooooooooooo",
    "gggggggooggggggg",
    "ggggggoyyogggggg",
    "gggggoyffyoggggg",
    "ggggooyffyooogggg"[:16],
    "gggggoyffyoggggg",
    "ggggggoyyogggggg",
    "gggggggooggggggg",
]
SHRINE_TOP_R = [
    "gggggggggggggggg",
    "nngggggggggggggg",
    "nnnnnnnggggggggg",
    "nnnnnnnoggggggggg"[:16],
    "oooooooggggggggg",
    "gggggggggggggggg",
    "nnnnnngggggggggg",
    "nnnnnngggggggggg",
    "oooooogggggggggg",
    "gggggggggggggggg",
    "oSSSSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
    "oSssSogggggggggg",
]
SHRINE_BOT_L = [
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "ppppppppppoSssSo",
    "pppppppppoSSSSSo",
    "ppppppppoSSSSSSS",
    "pppppppooxxxxxxx",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]
SHRINE_BOT_M = [
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppoooooooooppppp"[:16],
    "pppoSSSSSSSSoppp",
    "pppoSssyysssoppp",
    "pppoSsyYYysSoppp",
    "pppoSsyYYysSoppp",
    "pppoSssyysssoppp",
    "pppoSssssssSoppp",
    "pppoSSSSSSSSoppp",
    "pppoxxxxxxxxoppp",
    "pppoooooooooppp."[:16],
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]
SHRINE_BOT_R = [
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSssSopppppppppp",
    "oSSSSSopppppppppp"[:16],
    "SSSSSSSopppppppp",
    "xxxxxxxoopppppppp"[:16],
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
    "pppppppppppppppp",
]

# Marble column, authored upright like the trees.
COLUMN = [
    "..pppppppppppp..",
    ".pPPPPPPPPPPPPp.",
    ".pPPPPPPPPPPPPp.",
    "..pppppppppppp..",
    "...pPPPPPPPPp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "...pPpPPpPPpp...",
    "..pppppppppppp..",
    ".pPPPPPPPPPPPPp.",
    ".pPPPPPPPPPPPPp.",
    "..pppppppppppp..",
    "..hhhhhhhhhhhh..",
    "................",
]

RUBBLE = [
    "gggggggggggggggg",
    "ggggggggggggggGg",
    "gggppppgggggpppg",
    "ggpPPPPpgggpPPpg",
    "ggpPPPPpggpPPPpg",
    "gghppppggghpppgg",
    "gggggggggggggggg",
    "ggpppppgggggggGg",
    "gpPPPPPpgggppggg",
    "gpPPPPPpggpPPpgg",
    "ghpppppgghpppggg",
    "gggggggggggggggg",
    "gGggggggggggggGg",
    "gggggggggggggggg",
    "gggggggggggggggg",
    "gggggggggggggggg",
]

FOUNTAIN = [
    "SSSSSSSSSSSSSSSS",
    "SxxxxxxxxxxxxxxS",
    "SxwwwwwwwwwwwwxS",
    "SxwWWwwwwwwWWwxS",
    "SxwwwwWWWwwwwwxS",
    "SxwwwSSSSSwwwwxS",
    "SxwwSSjjjSSwwwxS",
    "SxwwSjmmmjSwwwxS",
    "SxwwSjmmmjSwwwxS",
    "SxwwSSjjjSSwwwxS",
    "SxwwwSSSSSwwwwxS",
    "SxwwwwWWWwwwwwxS",
    "SxwWWwwwwwwWWwxS",
    "SxwwwwwwwwwwwwxS",
    "SxxxxxxxxxxxxxxS",
    "SSSSSSSSSSSSSSSS",
]

LEDGE = [
    "gggggggggggggggg",
    "hhhhhhhhhhhhhhhh",
    "qqqqqqqqqqqqqqqq",
    "PqqPqqqqPqqqqPqq",
    "qqqqqqqqqqqqqqqq",
    "qqqqqqqqqqqqqqqq",
    "hhhhhhhhhhhhhhhh",
    "gGggggghgggGgggg",
    "gggggggggggggggg",
    "gggGgggggghggggg",
    "gggggggggggggggg",
    "gGgggghgggggggGg",
    "gggggggggggggggg",
    "ggghggggggGggggg",
    "gggggggggggggggg",
    "gGggggghgggGgggg",
]


def build():
    """Create every tile surface once, after the display is initialised."""
    t = {}
    t["grass"] = ground_tile(P.GRASS, P.GRASS_L, P.GRASS_D)
    t["path"] = ground_tile(P.PATH, P.PATH_L, P.PATH_D)
    t["sand"] = ground_tile(P.SAND, (244, 232, 190), (204, 188, 144))
    t["floor"] = ground_tile(P.STONE, P.STONE_L, P.STONE_D)
    for name, art in [
        ("tallgrass", TALLGRASS), ("tree", TREE), ("flowers", FLOWERS),
        ("water", WATER), ("water_b", WATER_B), ("rock", ROCK), ("sign", SIGN),
        ("roof_l", ROOF_L_), ("roof_m", ROOF_M), ("roof_r", ROOF_R),
        ("wall", WALL_PLAIN), ("window", WALL_WINDOW), ("door", DOOR),
        ("shrine_tl", SHRINE_TOP_L), ("shrine_tm", SHRINE_TOP_M),
        ("shrine_tr", SHRINE_TOP_R), ("shrine_bl", SHRINE_BOT_L),
        ("shrine_bm", SHRINE_BOT_M), ("shrine_br", SHRINE_BOT_R),
        ("fountain", FOUNTAIN), ("ledge", LEDGE),
        ("column", COLUMN), ("rubble", RUBBLE),
    ]:
        t[name] = make(art, PAL)
    return t
